#!/usr/bin/env python3
"""Build the #743 artifacts from the tree and one committed classification: the responsibility map
(docs/research/v0.23-cleanup/743-responsibilities.tsv) and the work unit's manifest.

Every figure is computed from `tests/structure.sh --raw` run against the worktree; nothing here is typed by hand
except the responsibility each function is assigned, which is the judgment the issue asks for and which the suite
holds to the tree.
"""
import os, subprocess, sys, collections
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from classification import RESP

args = [a for a in sys.argv[1:] if not a.startswith("--")]
flags = {a for a in sys.argv[1:] if a.startswith("--")}
W = args[0]
BASE = args[1] if len(args) > 1 else "origin/master"
# --map-only regenerates just the responsibility map, from the tree alone, so a test can check that the committed
# map is what this generator produces without cloning the repository for the before/after measurements.
MAP_ONLY = "--map-only" in flags
OUT = next((a.split("=", 1)[1] for a in flags if a.startswith("--out=")), W)
ORDER = ["argument-parsing", "routing-dispatch", "source-collection", "canonicalization", "domain-semantics",
         "evidence-authority", "formatting-reporting", "compatibility-fallback"]
GLOSS = {
    "argument-parsing": "reads flags and arguments",
    "routing-dispatch": "resolves a verb and loads what it needs",
    "source-collection": "reads a source of truth (git, gh, the filesystem) and returns it unjudged",
    "canonicalization": "normalizes what was read into this repository's vocabulary",
    "domain-semantics": "owns a rule about what the facts mean",
    "evidence-authority": "decides what the evidence is admissible for",
    "formatting-reporting": "renders",
    "compatibility-fallback": "keeps an older shape working",
}

def sh(*cmd, cwd=W):
    return subprocess.run(list(cmd), cwd=cwd, capture_output=True, text=True).stdout

def raw_at(tree_dir):
    out = sh("bash", "tests/structure.sh", "--raw", cwd=tree_dir)
    funcs, used, size = {}, {}, 0
    for line in out.split("\n"):
        p = line.split("\t")
        if p[0] == "FUNC": funcs[p[1]] = int(p[2])
        elif p[0] == "USED": used[p[1]] = p[3].split()
        elif p[0] == "SIZE": size = int(p[1])
    return funcs, used, size

funcs, used, _ = raw_at(W)
resp_of = {n: r for r, names in RESP.items() for n in names}
missing = sorted(set(funcs) - set(resp_of))
ghosts = sorted(set(resp_of) - set(funcs))
if missing or ghosts:
    raise SystemExit(f"classification does not match the tree: unclassified={missing} absent={ghosts}")

# --- the map
rows = []
for n in sorted(funcs):
    verbs = used.get(n, [])
    rows.append((n, resp_of[n], str(funcs[n]), str(len(verbs)), ";".join(verbs) if verbs else "-"))
hdr = """# Spark dispatcher responsibility map (#743) — generated by docs/research/v0.23-cleanup/tools/build-responsibilities,
# checked by tests/test-runtime-responsibilities.sh. One row per function in plugins/spark/bin/spark.
#
# responsibility is the issue's vocabulary: argument-parsing, routing-dispatch, source-collection,
# canonicalization, domain-semantics, evidence-authority, formatting-reporting, compatibility-fallback.
# A body that both reads and renders is assigned to the half it owns; the buckets are not disjoint in this code.
#
# function <TAB> responsibility <TAB> body lines <TAB> verbs referencing it <TAB> those verbs (;-separated, or -)
"""
os.makedirs(os.path.join(OUT, "docs/research/v0.23-cleanup"), exist_ok=True)
with open(os.path.join(OUT, "docs/research/v0.23-cleanup/743-responsibilities.tsv"), "w") as fh:
    fh.write(hdr + "".join("\t".join(r) + "\n" for r in rows))
if MAP_ONLY:
    print("map only:", len(rows), "functions")
    raise SystemExit(0)

by_resp = collections.Counter(resp_of[n] for n in funcs)
lines_by_resp = collections.Counter()
for n in funcs: lines_by_resp[resp_of[n]] += funcs[n]
total_fns, total_lines = len(funcs), sum(funcs.values())
shared = sorted((n for n in funcs if len(used.get(n, [])) >= 3), key=lambda n: -len(used[n]))
local = [n for n in funcs if len(used.get(n, [])) == 1]

# --- the same measurements at the base commit, for a before/after that is this unit's
base_sha = sh("git", "merge-base", BASE, "HEAD").strip()
tmp = subprocess.run(["mktemp", "-d"], capture_output=True, text=True).stdout.strip()
subprocess.run(["git", "clone", "-q", "--shared", "--no-checkout", W, tmp + "/tree"], check=True)
subprocess.run(["git", "-C", tmp + "/tree", "checkout", "-q", "--detach", base_sha], check=True)
base_funcs, base_used, _ = raw_at(tmp + "/tree")
base_bytes = int(sh("stat", "-c%s", "plugins/spark/bin/spark").strip() or 0)
b_bytes = len(subprocess.run(["git", "show", f"{base_sha}:plugins/spark/bin/spark"], cwd=W, capture_output=True).stdout)
b_exec = len(subprocess.run(["git", "show", f"{base_sha}:plugins/spark/lib/execution.sh"], cwd=W, capture_output=True).stdout)
now_exec = int(sh("stat", "-c%s", "plugins/spark/lib/execution.sh").strip() or 0)
subprocess.run(["rm", "-rf", tmp], check=False)

file_lines_now = int(sh("bash", "-c", "wc -l < plugins/spark/bin/spark").strip() or 0)
file_lines_base = len(subprocess.run(["git", "show", f"{base_sha}:plugins/spark/bin/spark"], cwd=W, capture_output=True).stdout.split(b"\n")) - 1
d_body = total_lines - sum(base_funcs.values()); d_file = file_lines_now - file_lines_base
body_note = ("Function bodies shrank by %d lines while the file grew by %d: the duplicated code is gone and what "
             "replaced it is documented at the top level, outside any body." % (-d_body, d_file)) if d_body < 0 < d_file else (
             "Body lines moved by %+d and file lines by %+d." % (d_body, d_file))
resp_tbl = "\n".join(f"| `{r}` | {by_resp[r]} | {lines_by_resp[r]:,} | {GLOSS[r]} |" for r in ORDER)
shared_tbl = "\n".join(f"| `{n}` | {len(used[n])} | `{resp_of[n]}` |" for n in shared[:10])

manifest = f"""# Runtime surface after canonicalization (v0.23 cleanup, #743)

**Rule.** An extraction or removal earns its place only by removing dead code, eliminating duplicate semantics,
creating one canonical primitive with several consumers, lowering change fanout, or making a boundary testable
with less context. Moving duplication into more files is not one of them, so this unit removes duplicate readers
and adds no module.

**The map comes first.** `docs/research/v0.23-cleanup/743-responsibilities.tsv` assigns every one of the
dispatcher's {total_fns} functions to exactly one of the issue's eight responsibilities, with its body length and
the verbs that reference it. `tests/test-runtime-responsibilities.sh` holds the map to the tree: a function added,
removed or renamed fails the suite until the map says where it belongs. The buckets are not disjoint in this code —
`governance_validate`, `di_grade` and `release_gate_projection` each collect, canonicalize, judge and render in one
body — so each is assigned to the half it owns, and that is stated rather than smoothed over.

| Responsibility | Functions | Body lines | What it owns |
|---|---|---|---|
{resp_tbl}

Two buckets hold {by_resp['domain-semantics'] + by_resp['source-collection']} of {total_fns} functions and
{lines_by_resp['domain-semantics'] + lines_by_resp['source-collection']:,} of {total_lines:,} body lines. That
concentration is the issue's premise, and it is also the trap: for `cmd_doctor`, `cmd_next` and `cmd_labels` the
rules *are* the product, and there is no lower layer to defer them to. Relocating them would move ownership
without reducing it.

**What the reference graph names as shared.** A function several verbs reference is a canonical primitive by
demonstration, and must not be duplicated back into a module:

| Primitive | Verbs referencing it | Responsibility |
|---|---|---|
{shared_tbl}

## What this unit changed

Three duplicate readers became one each. Each is a fact that was read in two or three places with byte-identical
bodies — #739's rule, applied to what #739 left behind.

- **`intent_liveness`** — `triage_rows` and `rec_rows` each walked the issues a recorded next action names and
  tallied closed/open/unread with an identical `gh api …/issues/<n> --jq .state` loop. One reader now returns the
  tally; each caller keeps its own projection, and both still tell "no `gh` at all" apart from "`gh` could not
  answer", because that distinction lives in the caller where it is rendered.
- **`di_trunk`** — `cmd_resume` carried its own copy of the remote-trunk idiom (`refs/remotes/origin/HEAD`, else
  `origin/master`/`origin/main`). It calls the primitive now. `repo_trunk` stays separate deliberately: it answers
  the *local* trunk name without touching the network, and collapsing the two would make an offline triage depend
  on a remote ref.
- **`json_escape`** — three identical escapers existed as nested functions (`cmd_state`, `cmd_telemetry`,
  `cmd_budget`). One lives in the dispatcher now, where modules already reach for shared primitives and where
  `tests/test-runtime-modules.sh` forbids a module restating one. `js` is untouched: it *strips* quotes and
  backslashes rather than escaping them, and merging them would silently change `spark doctor --requirements --json`.

## Before and after

| | Functions | Body lines | File lines | `bin/spark` bytes | `lib/execution.sh` bytes |
|---|---|---|---|---|---|
| before (`{base_sha[:7]}`) | {len(base_funcs)} | {sum(base_funcs.values()):,} | {file_lines_base:,} | {b_bytes:,} | {b_exec:,} |
| after | {total_fns} | {total_lines:,} | {file_lines_now:,} | {base_bytes:,} | {now_exec:,} |

{body_note} Neither number is the measure #743 asks for, and the manifest does not argue from them. What fell is
the number of readers of each fact — two to one, two to one, three to one — and with it the number of places a
change to any of them has to land.

**Change fanout, measured the only way this repository can.** A change to how the runtime reads an issue's state
touched two functions in two verbs' paths before and touches one now; the remote-trunk idiom, two and now one;
JSON escaping, three and now one. No module count changed, so no verb loads more source than before, and
`tests/test-runtime-modules.sh` still asserts the loaded bytes exactly.

## What was rejected, and why

- **Extracting a `doctor` module** (1,296 lines the graph names as single-verb) — defensible under the issue's
  second clause, but it removes no duplication, and its payoff must be argued in `runtime_peak_source_bytes` and
  `tests/bench.sh` numbers rather than in line counts. It is a separate unit with its own measurement, not a
  rider on this one.
- **Extracting argument parsing** — the 240 parse lines are per-verb: distinct usage text, distinct flags,
  distinct `-h` bodies. A shared parser would either normalize user-visible strings, which #743 forbids, or take
  them as parameters and save nothing.
- **The legacy state keys** — #738 already ruled that removing them needs evidence no consumer has an unmigrated
  file, or a deprecation window, and that evidence is unknowable from this repository.
- **Anything #738 marked do-not-delete** — the `enhancement` alias and `--prune-deprecated` are public CLI
  behaviour; every `cmd_*` and `fp_hot_*` is reached by name from the dispatch table.

## Acceptance, item by item

- **Responsibilities mapped before change** — the map above, generated and machine-checked.
- **Every removal cites its evidence** — each of the three names the byte-identical bodies it replaced.
- **The dispatcher parses, routes, loads and reports rather than owning duplicate semantics** — the duplication
  removed is exactly the read-a-fact-twice kind; where the dispatcher still owns rules, the map says so and the
  manifest says why relocating them would not help.
- **Counts recorded before and after, not as the sole measure** — the table above, with the reader counts that
  actually fell.
- **Fanout compared where mechanically practical** — reader counts per fact, above.
- **Module count rises only when duplication or change surface falls** — no module was added.
- **No public behaviour or authority guarantee changed** — no CLI semantics touched; `js` and `repo_trunk` left
  alone deliberately.
- **No cleanup-only refactor became a rewrite** — three primitives, no restructuring.
- **Focused and full suites green on the exact HEAD** — recorded in the pull request.
"""
open(os.path.join(W, "docs/research/v0.23-cleanup/743-runtime-surface.md"), "w").write(manifest)
print("functions", total_fns, "lines", total_lines, "base", len(base_funcs), sum(base_funcs.values()))
