#!/usr/bin/env python3
"""Build the #743 artifacts from the tree and two committed classifications: the runtime responsibility map, the
same map at the commit this branch left, and the work unit's manifest.

Scope is the whole runtime — the dispatcher and all three modules — because #743 asks for the dispatcher/runtime
surface, and a fact canonicalized in the dispatcher is consumed across module boundaries.

Every figure is computed here: function inventories come from `tests/structure.sh --raw` run per file (the
repository's own scanner, so the map cannot drift from what the repo reports), consumers from a whole-word scan of
every runtime body, and the before-side from a pristine checkout of the base commit. Nothing is typed by hand
except each function's responsibility, which is the judgment the issue asks for and which the suite holds to the
tree.

usage: build-responsibilities.py <worktree> [base-ref] [--map-only] [--out=<dir>]
"""
import os, re, subprocess, sys, collections
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from classification import RESP
from classification_modules import MODULE_RESP

args = [a for a in sys.argv[1:] if not a.startswith("--")]
flags = {a for a in sys.argv[1:] if a.startswith("--")}
W = args[0]
BASE = args[1] if len(args) > 1 else "origin/master"
MAP_ONLY = "--map-only" in flags
OUT = next((a.split("=", 1)[1] for a in flags if a.startswith("--out=")), W)

FILES = ["plugins/spark/bin/spark", "plugins/spark/lib/execution.sh",
         "plugins/spark/lib/planning.sh", "plugins/spark/lib/repository.sh"]
ORDER = ["argument-parsing", "routing-dispatch", "source-collection", "canonicalization", "domain-semantics",
         "evidence-authority", "formatting-reporting", "compatibility-fallback"]
GLOSS = {
    "argument-parsing": "reads flags and arguments",
    "routing-dispatch": "resolves a verb and loads what it needs",
    "source-collection": "reads a source of truth (git, gh, the filesystem) and returns it unjudged",
    "canonicalization": "normalizes what was read into this repository's vocabulary",
    "domain-semantics": "owns a rule about what the facts mean",
    "evidence-authority": "decides what the evidence is admissible for",
    "formatting-reporting": "renders",
    "compatibility-fallback": "keeps an older shape working",
}
RESP_OF = {n: r for r, names in RESP.items() for n in names}
for r, names in MODULE_RESP.items():
    for n in names: RESP_OF[n] = r


def sh(*cmd, cwd=W):
    return subprocess.run(list(cmd), cwd=cwd, capture_output=True, text=True).stdout


def inventory(tree):
    """Every runtime function: name -> (file, body lines). The repository's scanner is run once per file."""
    fns = {}
    for f in FILES:
        for line in sh("bash", "tests/structure.sh", "--raw", f, cwd=tree).split("\n"):
            p = line.split("\t")
            if p[0] == "FUNC": fns[p[1]] = (f, int(p[2]))
    return fns


def consumers(tree, fns):
    """Who references whom across the whole runtime. Whole-word textual references between function bodies — the
    weaker-than-a-call-graph model tests/structure.sh documents, where a name in a comment counts and a name
    reached through a variable does not — widened from one file to four."""
    bodies, out = {}, collections.defaultdict(set)
    for f in FILES:
        cur, buf = None, []
        for line in open(os.path.join(tree, f)).read().split("\n"):
            m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\(\) \{", line)
            if m:
                if cur: bodies[cur] = "\n".join(buf)
                cur, buf = m.group(1), []
                continue
            if line.startswith("}") and cur:
                bodies[cur] = "\n".join(buf); cur, buf = None, []
                continue
            if cur: buf.append(line)
        if cur: bodies[cur] = "\n".join(buf)
    for holder, body in bodies.items():
        for n in fns:
            if n == holder: continue
            if re.search(r"(?<![A-Za-z0-9_])" + re.escape(n) + r"(?![A-Za-z0-9_])", body):
                out[n].add(holder)
    return out


def rows_for(tree):
    fns = inventory(tree)
    unmapped = sorted(n for n in fns if n not in RESP_OF)
    if unmapped:
        raise SystemExit("unclassified runtime functions: " + " ".join(unmapped))
    cons = consumers(tree, fns)
    rows = []
    for n in sorted(fns):
        f, body = fns[n]
        cs = sorted(cons.get(n, ()))
        verbs = sorted(c for c in cs if c.startswith("cmd_"))
        rows.append((n, f, RESP_OF[n], str(body), str(len(cs)), ";".join(cs) if cs else "-",
                     ";".join(verbs) if verbs else "-"))
    return fns, rows


HDR = """# Spark runtime responsibility map (#743) — generated by
# docs/research/v0.23-cleanup/tools/build-responsibilities.py, checked by tests/test-runtime-responsibilities.sh.
# One row per function in the dispatcher and all three modules.
#
# responsibility is the issue's vocabulary: argument-parsing, routing-dispatch, source-collection,
# canonicalization, domain-semantics, evidence-authority, formatting-reporting, compatibility-fallback.
# A body that both reads and renders is assigned to the half it owns; the buckets are not disjoint in this code.
#
# consumers are whole-word textual references from other runtime bodies, across module boundaries — the model
# tests/structure.sh documents (a name in a comment counts; a name reached through a variable does not), widened
# from one file to four. verbs are the cmd_* consumers among them.
#
# function <TAB> file <TAB> responsibility <TAB> body lines <TAB> consumer count <TAB> consumers <TAB> verbs
"""


def write_map(path, rows):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(HDR + "".join("\t".join(r) + "\n" for r in rows))


fns_after, rows_after = rows_for(W)
write_map(os.path.join(OUT, "docs/research/v0.23-cleanup/743-responsibilities.tsv"), rows_after)

base_sha = sh("git", "merge-base", BASE, "HEAD").strip()
tmp = subprocess.run(["mktemp", "-d"], capture_output=True, text=True).stdout.strip()
subprocess.run(["git", "clone", "-q", "--shared", "--no-checkout", W, tmp + "/tree"], check=True)
subprocess.run(["git", "-C", tmp + "/tree", "checkout", "-q", "--detach", base_sha], check=True)
fns_before, rows_before = rows_for(tmp + "/tree")
write_map(os.path.join(OUT, "docs/research/v0.23-cleanup/743-responsibilities-before.tsv"), rows_before)
subprocess.run(["rm", "-rf", tmp], check=False)

if MAP_ONLY:
    print("maps only:", len(rows_after), "functions after,", len(rows_before), "before")
    raise SystemExit(0)


def totals(fns):
    by_resp = collections.Counter(RESP_OF[n] for n in fns)
    lines_by = collections.Counter()
    for n, (_f, b) in fns.items(): lines_by[RESP_OF[n]] += b
    return by_resp, lines_by


after_resp, after_lines = totals(fns_after)
before_resp, before_lines = totals(fns_before)
n_after, n_before = len(fns_after), len(fns_before)
l_after = sum(b for _f, b in fns_after.values())
l_before = sum(b for _f, b in fns_before.values())
per_file_after = collections.Counter(f for f, _b in fns_after.values())
per_file_before = collections.Counter(f for f, _b in fns_before.values())

resp_tbl = "\n".join(
    f"| `{r}` | {before_resp[r]} | {after_resp[r]} | {before_lines[r]:,} | {after_lines[r]:,} | {GLOSS[r]} |"
    for r in ORDER)
file_tbl = "\n".join(f"| `{f}` | {per_file_before[f]} | {per_file_after[f]} |" for f in FILES)
cons_after = {r[0]: int(r[4]) for r in rows_after}
shared = sorted((n for n in fns_after if cons_after.get(n, 0) >= 8), key=lambda n: (-cons_after[n], n))[:10]
shared_tbl = "\n".join(f"| `{n}` | {cons_after[n]} | `{RESP_OF[n]}` |" for n in shared)


def consumers_of(name, rows):
    for r in rows:
        if r[0] == name: return r[5].split(";") if r[5] != "-" else []
    return []


je_after = consumers_of("json_escape", rows_after)
d_fns, d_body = n_after - n_before, l_after - l_before

manifest = f"""# Runtime surface after canonicalization (v0.23 cleanup, #743)

**Rule.** An extraction or removal earns its place only by removing dead code, eliminating duplicate semantics,
creating one canonical primitive with several consumers, lowering change fanout, or making a boundary testable
with less context. Moving duplication into more files is not one of them, so this unit removes duplicate readers
and adds no module.

**The map comes first, and it covers the whole runtime.** `docs/research/v0.23-cleanup/743-responsibilities.tsv`
assigns every one of the {n_after} functions in the dispatcher and its three modules to exactly one of the issue's
eight responsibilities, with its body length, everything in the runtime that references it, and the verbs among
those. `743-responsibilities-before.tsv` is the same map at `{base_sha[:7]}`, the commit this branch left, so the
before-change baseline is a map and not a pair of totals. Both are generated from `tests/structure.sh --raw` run
per file, and `tests/test-runtime-responsibilities.sh` holds both to their trees: a function added, removed or
renamed fails the suite until the map says where it belongs.

The buckets are not disjoint in this code — `governance_validate`, `di_grade` and `release_gate_projection` each
collect, canonicalize, judge and render in one body — so each function is assigned to the half it owns, and that is
stated rather than smoothed over.

| Responsibility | Functions before | after | Body lines before | after | What it owns |
|---|---|---|---|---|---|
{resp_tbl}

| File | Functions before | after |
|---|---|---|
{file_tbl}

Module count is unchanged at three. The runtime holds {n_after} functions and {l_after:,} body lines, against
{n_before} and {l_before:,} before: {d_fns:+d} functions, {d_body:+d} body lines.

Two buckets hold {after_resp['domain-semantics'] + after_resp['source-collection']} of {n_after} functions and
{after_lines['domain-semantics'] + after_lines['source-collection']:,} of {l_after:,} body lines. That
concentration is the issue's premise, and it is also the trap: for `cmd_doctor`, `cmd_next` and `cmd_labels` the
rules *are* the product, and there is no lower layer to defer them to. Relocating them would move ownership
without reducing it.

**What the graph names as shared.** A function many runtime bodies reference is a canonical primitive by
demonstration, and must not be duplicated back into a module:

| Primitive | Runtime consumers | Responsibility |
|---|---|---|
{shared_tbl}

## What this unit changed

Three duplicate readers became one each. Each is a fact that was read in two or three places with byte-identical
bodies — #739's rule, applied to what #739 left behind.

- **`intent_liveness`** — `triage_rows` and `rec_rows` each walked the issues a recorded next action names and
  tallied closed/open/unread with an identical `gh api …/issues/<n> --jq .state` loop. One reader now returns the
  tally; each caller keeps its own projection, and both still tell "no `gh` at all" apart from "`gh` could not
  answer", because that distinction lives in the caller where it is rendered.
- **`di_trunk`** — `cmd_resume` carried its own copy of the remote-trunk idiom (`refs/remotes/origin/HEAD`, else
  `origin/master`/`origin/main`). It calls the primitive now. `repo_trunk` stays separate deliberately: it answers
  the *local* trunk name without touching the network, and collapsing the two would make an offline triage depend
  on a remote ref.
- **`json_escape`** — three identical escapers existed as nested functions (`cmd_state` in the dispatcher,
  `cmd_telemetry` and `cmd_budget` in `lib/execution.sh`). One lives in the dispatcher now, where modules already
  reach for shared primitives and where `tests/test-runtime-modules.sh` forbids a module restating one. The map
  shows the result across the module boundary: its runtime consumers are {', '.join('`' + c + '`' for c in je_after)}.
  `js` is untouched: it *strips* quotes and backslashes rather than escaping them, and merging them would silently
  change `spark doctor --requirements --json`.

**Change fanout.** A change to how the runtime reads an issue's state touched two bodies before and touches one
now; the remote-trunk idiom, two and now one; JSON escaping, three and now one. The consumer columns in the two
maps carry those numbers per function, computed the same way on both sides, so the comparison is like with like.

## What was rejected, and why

- **Extracting a `doctor` module** (1,296 lines the graph names as single-verb) — defensible under the issue's
  second clause, but it removes no duplication, and its payoff must be argued in `runtime_peak_source_bytes` and
  `tests/bench.sh` numbers rather than in line counts. It is a separate unit with its own measurement, not a
  rider on this one.
- **Extracting argument parsing** — the parse lines are per-verb: distinct usage text, distinct flags, distinct
  `-h` bodies. A shared parser would either normalize user-visible strings, which #743 forbids, or take them as
  parameters and save nothing.
- **The legacy state keys** — #738 already ruled that removing them needs evidence no consumer has an unmigrated
  file, or a deprecation window, and that evidence is unknowable from this repository.
- **Anything #738 marked do-not-delete** — the `enhancement` alias and `--prune-deprecated` are public CLI
  behaviour; every `cmd_*` and `fp_hot_*` is reached by name from the dispatch table.

## Acceptance, item by item

- **Responsibilities mapped before change** — `743-responsibilities-before.tsv`, the same map at the base commit,
  generated by the same tool and checked by the same suite.
- **Every removal cites its evidence** — each of the three names the byte-identical bodies it replaced.
- **The dispatcher parses, routes, loads and reports rather than owning duplicate semantics** — the duplication
  removed is exactly the read-a-fact-twice kind; where the dispatcher still owns rules, the map says so and the
  manifest says why relocating them would not help.
- **Counts recorded before and after, not as the sole measure** — the tables above, with the consumer counts that
  actually fell.
- **Fanout compared where mechanically practical** — consumer counts per function, on both sides, computed across
  module boundaries.
- **Module count rises only when duplication or change surface falls** — module count is unchanged at three.
- **No public behaviour or authority guarantee changed** — no CLI semantics touched; `js` and `repo_trunk` left
  alone deliberately.
- **No cleanup-only refactor became a rewrite** — three primitives, no restructuring.
- **Focused and full suites green on the exact HEAD** — recorded in the pull request.
"""
open(os.path.join(OUT, "docs/research/v0.23-cleanup/743-runtime-surface.md"), "w").write(manifest)
print("after", n_after, l_after, "before", n_before, l_before, "json_escape consumers", len(je_after))
