#!/usr/bin/env bash
# The runtime's responsibility map is held to the tree (#743): every function in the dispatcher and its three
# modules classified exactly once, no name that does not exist, the before-change map generated by the same tool
# from the base commit, every figure on the manifest recomputed here, and the canonical primitives still canonical.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
. "$ROOT/tests/lib.sh"

MAP="$ROOT/docs/research/v0.23-cleanup/743-responsibilities.tsv"
MAP_BEFORE="$ROOT/docs/research/v0.23-cleanup/743-responsibilities-before.tsv"
MAN="$ROOT/docs/research/v0.23-cleanup/743-runtime-surface.md"
GEN="$ROOT/docs/research/v0.23-cleanup/tools/build-responsibilities.py"
SPARK="$ROOT/plugins/spark/bin/spark"
EXEC="$ROOT/plugins/spark/lib/execution.sh"
FILES="plugins/spark/bin/spark plugins/spark/lib/execution.sh plugins/spark/lib/planning.sh plugins/spark/lib/repository.sh plugins/spark/lib/facts.sh"
for f in "$MAP" "$MAP_BEFORE" "$MAN"; do
  [ -f "$f" ] && ok || bad "$(basename "$f") is committed"
done
rows() { grep -v '^#' "$MAP" | grep -v '^$'; }
rows_before() { grep -v '^#' "$MAP_BEFORE" | grep -v '^$'; }

# --- shape and closed vocabulary, on both maps
for which in after before; do
  case "$which" in after) src=rows ;; before) src=rows_before ;; esac
  assert_eq "$which: every responsibility is in the closed vocabulary" "" \
    "$($src | cut -f5 | grep -vE '^(argument-parsing|routing-dispatch|source-collection|canonicalization|domain-semantics|evidence-authority|formatting-reporting|compatibility-fallback)$' | sort -u | tr '\n' ' ')"
  assert_eq "$which: every row has ten fields" "" "$($src | awk -F'\t' 'NF != 10 {print $1}' | tr '\n' ' ')"
  assert_eq "$which: every scope is top-level or nested" "" \
    "$($src | cut -f3 | grep -vxE 'top-level|nested' | sort -u | tr '\n' ' ')"
  assert_eq "$which: every nested function names an owner that the map knows" "" \
    "$($src | awk -F'\t' '$3 == "nested" {print $4}' | sort -u | while IFS= read -r o; do [ -z "$o" ] && continue; $src | cut -f1 | grep -qx "$o" || printf '%s ' "$o"; done)"
  assert_eq "$which: no function is classified twice" "" "$($src | cut -f1 | sort | uniq -d | tr '\n' ' ')"
  assert_eq "$which: every file named is a runtime file" "" \
    "$($src | cut -f2 | sort -u | grep -vE '^plugins/spark/(bin/spark|lib/(execution|planning|repository|facts)\.sh)$' | tr '\n' ' ')"
done

# --- the map is the tree's: same functions, same files, same body lengths, across every runtime file
tree_rows=""
for f in $FILES; do
  while IFS=$'\t' read -r kind name body; do
    [ "$kind" = FUNC ] || continue
    tree_rows="$tree_rows$name	$f	$body
"
  done < <(cd "$ROOT" && bash tests/structure.sh --raw "$f")
done
# the repository's scanner reports top-level definitions only and stays the authority for that half
assert_eq "the map's top-level rows are exactly the scanner's functions" \
  "$(printf '%s' "$tree_rows" | cut -f1 | sort)" "$(rows | awk -F'\t' '$3 == "top-level" {print $1}' | sort)"
assert_eq "every top-level file and body length is the scanner's" \
  "$(printf '%s' "$tree_rows" | sort)" "$(rows | awk -F'\t' '$3 == "top-level" {printf "%s\t%s\t%s\n", $1, $2, $6}' | sort)"
# nested definitions are functions too, and the map must carry them: this is what a top-level-only inventory missed
[ "$(rows | awk -F'\t' '$3 == "nested"' | grep -c .)" -ge 1 ] && ok || bad "the map records no nested function"
assert_eq "the nested row printer inside the budget verb is mapped" "1" \
  "$(rows | awk -F'\t' '$1 == "bg_row" && $3 == "nested" && $4 == "cmd_budget"' | grep -c .)"
nested_in_tree="$(cd "$ROOT" && grep -hE '^[[:space:]]+[A-Za-z_][A-Za-z0-9_]*\(\) \{' $FILES | sed -E 's/^[[:space:]]*([A-Za-z_][A-Za-z0-9_]*)\(\).*/\1/' | sort -u)"
assert_eq "every nested definition in the tree is mapped" "$nested_in_tree" \
  "$(rows | awk -F'\t' '$3 == "nested" {print $1}' | sort -u)"

# --- the before map is a real baseline: it names the base commit's runtime, not this one's
assert_eq "the manifest names the commit the before map was taken at" "1" \
  "$(grep -c 'is the same map at `[0-9a-f]\{7\}`' "$MAN")"
before_sha="$(sed -nE 's/.*is the same map at `([0-9a-f]{7})`.*/\1/p' "$MAN" | head -1)"
if (cd "$ROOT" && git cat-file -e "$before_sha^{commit}" 2>/dev/null); then
  ok
  # A module introduced after the pin is absent from the baseline, and that
  # absence is the growth the before/after figures exist to show. What must hold
  # is the other direction: every file the BEFORE MAP names has to exist at the
  # commit it claims to be a map of, or the baseline is not a baseline.
  for f in $(rows_before | cut -f2 | sort -u); do
    (cd "$ROOT" && git cat-file -e "$before_sha:$f" 2>/dev/null) && ok || bad "the before map's commit has no $f"
  done
else
  echo "  · the before map's commit is not in this checkout; the generator gate below still regenerates it"
fi

# --- the manifest's figures are the maps'
for r in argument-parsing routing-dispatch source-collection canonicalization domain-semantics evidence-authority formatting-reporting compatibility-fallback; do
  na="$(rows | awk -F'\t' -v r="$r" '$5 == r {c++} END {print c+0}')"
  nb="$(rows_before | awk -F'\t' -v r="$r" '$5 == r {c++} END {print c+0}')"
  la="$(rows | awk -F'\t' -v r="$r" '$5 == r {s+=$6} END {printf "%d", s}' | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')"
  lb="$(rows_before | awk -F'\t' -v r="$r" '$5 == r {s+=$6} END {printf "%d", s}' | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')"
  grep -qF -- "| \`$r\` | $nb | $na | $lb | $la |" "$MAN" && ok || bad "the manifest's row for $r is not the maps' ($nb/$na functions, $lb/$la lines)"
done
for f in $FILES; do
  na="$(rows | awk -F'\t' -v f="$f" '$2 == f {c++} END {print c+0}')"
  nb="$(rows_before | awk -F'\t' -v f="$f" '$2 == f {c++} END {print c+0}')"
  grep -qF -- "| \`$f\` | $nb | $na |" "$MAN" && ok || bad "the manifest's file row for $f is not the maps' ($nb/$na)"
done
n_after="$(rows | grep -c .)"
# The module count is derived here for the same reason the manifest derives it:
# pinned as a word, this assertion goes stale the moment a module is added, and
# a suite that must be edited to stay true is not checking anything.
n_mods="$(rows | cut -f2 | sort -u | grep -c '/lib/')"
case "$n_mods" in 1) mw=one ;; 2) mw=two ;; 3) mw=three ;; 4) mw=four ;; 5) mw=five ;; *) mw="$n_mods" ;; esac
grep -qF -- "the $n_after functions in the dispatcher and its $mw modules" "$MAN" && ok || bad "the manifest does not state the runtime function count $n_after over $mw modules"

# --- the page's account of the inventory change is the maps': names, not arithmetic
gone="$(comm -23 <(rows_before | cut -f1 | sort) <(rows | cut -f1 | sort))"
added="$(comm -13 <(rows_before | cut -f1 | sort) <(rows | cut -f1 | sort))"
for fn in $gone $added; do
  grep -qF -- "\`$fn\`" "$MAN" && ok || bad "the manifest does not name $fn, which the inventory change includes"
done
n_gone="$(printf '%s\n' "$gone" | grep -c .)"; n_added="$(printf '%s\n' "$added" | grep -c .)"
grep -qF -- "removes $n_gone definition(s)" "$MAN" && ok || bad "the manifest does not state that $n_gone definitions were removed"
grep -qF -- "adds $n_added" "$MAN" && ok || bad "the manifest does not state that $n_added definitions were added"
# a function present on both sides whose scope changed is a move, not an addition
moved=""
while IFS=$'\t' read -r fn _f scope _rest; do
  before_scope="$(rows_before | awk -F'\t' -v f="$fn" '$1 == f {print $3}')"
  [ -n "$before_scope" ] || continue
  [ "$before_scope" = "$scope" ] || moved="$moved $fn"
done < <(rows)
n_moved="$(printf '%s' "$moved" | wc -w | tr -d ' ')"
grep -qF -- "moves $n_moved" "$MAN" && ok || bad "the manifest does not state that $n_moved definitions moved scope"
assert_eq "the totals reconcile: before - removed + added = after" "$(rows | grep -c .)" \
  "$(( $(rows_before | grep -c .) - n_gone + n_added ))"

# --- the map headers describe the reference model the generator implements
for f in "$MAP" "$MAP_BEFORE"; do
  grep -q 'Comments are dropped' "$f" && ok || bad "$(basename "$f") does not state that comments are excluded from references"
  grep -q 'single-quoted strings are dropped' "$f" && ok || bad "$(basename "$f") does not state that single-quoted prose is excluded"
  assert_eq "$(basename "$f") does not claim comments count" "" "$(grep -c 'a name in a comment counts' "$f" | grep -v '^0$' || true)"
done

# --- the canonicalizations hold: one definition each, and the replaced copies are gone
for fn in intent_liveness di_trunk json_escape; do
  assert_eq "$fn is defined exactly once in the dispatcher" "1" "$(grep -c "^$fn() {" "$SPARK")"
done
assert_eq "no module restates the JSON escaper" "" \
  "$(grep -l 'json_escape_out\|bg_json_escape' "$ROOT"/plugins/spark/lib/*.sh 2>/dev/null | tr '\n' ' ')"
assert_eq "the issue-state read has one reader" "1" \
  "$(grep -c 'gh api "repos/{owner}/{repo}/issues/\$n" --jq .state' "$SPARK")"
# two readers, two facts: di_trunk answers the REMOTE trunk ref, repo_trunk the LOCAL trunk name (network-free,
# on brief's SessionStart path). Comments naming the ref do not count; executable lines do.
assert_eq "the trunk ref is read in exactly two places, one per fact" "2" \
  "$(grep -v '^ *#' "$SPARK" | grep -c 'refs/remotes/origin/HEAD')"
assert_eq "resume calls the remote-trunk reader" "1" \
  "$(awk '/^cmd_resume\(\) \{/, /^\}/' "$SPARK" | grep -c 'di_trunk "\$root"')"
assert_eq "resume does not resolve the ref itself" "0" \
  "$(awk '/^cmd_resume\(\) \{/, /^\}/' "$SPARK" | grep -v '^ *#' | grep -c 'refs/remotes/origin/HEAD')"

# --- the map proves the canonicalization across the module boundary, which a dispatcher-only graph could not
je="$(rows | awk -F'\t' '$1 == "json_escape" {print $9}')"
for consumer in cmd_state cmd_telemetry cmd_budget facts_envelope_tail facts_repository_fact facts_graph_entry facts_graph_fact; do
  case "$je" in
    *"$consumer"*) ok ;;
    *) bad "the map does not show $consumer consuming json_escape" ;;
  esac
done
grep -q 'json_escape' "$EXEC" && ok || bad "the execution module calls the canonical escaper"

# --- the primitives are used, not merely defined
for fn in intent_liveness di_trunk json_escape; do
  n="$(rows | awk -F'\t' -v f="$fn" '$1 == f {print $8}')"
  [ "${n:-0}" -ge 2 ] && ok || bad "$fn is defined but has fewer than two consumers"
done

# --- argument parsing is measured, not assigned: the column exists and the manifest's table is the map's
assert_eq "parse lines are non-negative integers" "" \
  "$(rows | awk -F'\t' '$7 !~ /^[0-9]+$/ {print $1}' | tr '\n' ' ')"
[ "$(rows | awk -F'\t' '{s+=$7} END {print s+0}')" -gt 0 ] && ok || bad "no function carries a parse line, which cannot be true"
# a body cannot contain more parse lines than it has lines; that inequality catches a scanner that loses a
# function's boundary and charges the lines after it to the wrong owner
for which in after before; do
  case "$which" in after) src=rows ;; before) src=rows_before ;; esac
  assert_eq "$which: no body has more parse lines than lines" "" \
    "$($src | awk -F'\t' '$7 > $6 {print $1 "(" $7 ">" $6 ")"}' | tr '\n' ' ')"
done
# a one-line function's consumers must name it on that one line — the edge a lost boundary invents
oneliners="$(rows | awk -F'\t' '$6 == 1 {print $1}')"
bad_edges=""
while IFS= read -r fn; do
  [ -n "$fn" ] || continue
  src_line="$(grep -h -m1 -E "^[[:space:]]*$fn\(\) \{" "$SPARK" "$ROOT"/plugins/spark/lib/*.sh 2>/dev/null || true)"
  [ -n "$src_line" ] || continue
  consumed="$(rows | awk -F'\t' -v f="$fn" '$9 != "-" { n = split($9, cs, ";"); for (i = 1; i <= n; i++) if (cs[i] == f) print $1 }')"
  while IFS= read -r target; do
    [ -n "$target" ] || continue
    case "$src_line" in *"$target"*) ;; *) bad_edges="$bad_edges $fn->$target" ;; esac
  done <<EOF_TARGETS
$consumed
EOF_TARGETS
done <<EOF_ONELINERS
$oneliners
EOF_ONELINERS
assert_eq "no one-line function consumes what its single line does not name" "" "$(printf '%s' "$bad_edges" | sed 's/^ //')"
assert_eq "the canonical escaper has exactly twelve consumers" "12" "$(rows | awk -F'\t' '$1 == "json_escape" {print $8}')"
for f in $FILES; do
  pa="$(rows | awk -F'\t' -v f="$f" '$2 == f {s+=$7} END {printf "%d", s}' | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')"
  pb="$(rows_before | awk -F'\t' -v f="$f" '$2 == f {s+=$7} END {printf "%d", s}' | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')"
  grep -qF -- "| \`$f\` | $pb | $pa |" "$MAN" && ok || bad "the manifest's parse row for $f is not the maps' ($pb/$pa)"
done

# --- a nested function's own arguments and its own references are its own, not its holder's
assert_eq "the nested row printer's one-line body carries its own argument reference" "1" \
  "$(rows | awk -F'\t' '$1 == "bg_row" {print $7}')"
assert_eq "the nested telemetry row printer carries its own too" "1" \
  "$(rows | awk -F'\t' '$1 == "tm_row" {print $7}')"
# every nested one-liner that uses a positional parameter must show at least one parse line
nested_args_missing=""
while IFS=$'\t' read -r fn file scope owner _resp body parse _n _cs _v; do
  [ "$scope" = nested ] || continue
  [ "$body" = 1 ] || continue
  line="$(grep -h -m1 -E "^[[:space:]]*$fn\(\) \{" "$SPARK" "$ROOT"/plugins/spark/lib/*.sh 2>/dev/null || true)"
  case "$line" in
    *'$1'*|*'$2'*|*'$@'*|*'$#'*) [ "$parse" -ge 1 ] || nested_args_missing="$nested_args_missing $fn" ;;
  esac
done < <(rows)
assert_eq "no nested one-liner using a positional parameter reports zero parse lines" "" \
  "$(printf '%s' "$nested_args_missing" | sed 's/^ //')"
# a nested function makes its own outgoing edges: the placement helpers reference each other, not only their holder
assert_eq "a nested helper is recorded as a consumer of its sibling" "1" \
  "$(rows | awk -F'\t' '$1 == "place" && $9 ~ /place_template/' | grep -c .)"

# --- the generator is runnable, and both committed maps are what it produces
[ -x "$GEN" ] && ok || bad "the map's generator is committed and executable"
[ -f "$ROOT/docs/research/v0.23-cleanup/tools/classification.py" ] && ok || bad "the dispatcher classification is committed under an importable name"
[ -f "$ROOT/docs/research/v0.23-cleanup/tools/classification_modules.py" ] && ok || bad "the module classification is committed under an importable name"
gen_out="$(mktemp -d)"
# the baseline is a fixed commit, and the map records it: regenerating with anything else would rebuild a
# different "before" the moment this branch merges and the branch point moves
pin="$(sed -nE 's/^# observed at ([0-9a-f]{40})$/\1/p' "$MAP_BEFORE" | head -1)"
[ -n "$pin" ] && ok || bad "the before map does not pin the commit it was observed at"
assert_eq "the pinned baseline is the commit the manifest names" "$before_sha" "${pin:0:7}"
(cd "$ROOT" && git cat-file -e "$pin^{commit}" 2>/dev/null) && ok || bad "the pinned baseline commit $pin is not in this repository"
if (cd "$ROOT" && python3 "$GEN" "$ROOT" "$pin" --map-only "--out=$gen_out" >/dev/null 2>&1); then
  assert_eq "the committed map is what the generator produces" "" \
    "$(diff "$MAP" "$gen_out/docs/research/v0.23-cleanup/743-responsibilities.tsv" | head -5 | tr '\n' ' ')"
  assert_eq "the committed before map is what the generator produces" "" \
    "$(diff "$MAP_BEFORE" "$gen_out/docs/research/v0.23-cleanup/743-responsibilities-before.tsv" | head -5 | tr '\n' ' ')"
else
  bad "the map's generator does not run"
fi
rm -rf "$gen_out"

# the DEFAULT invocation must find the pin on its own; passing it explicitly above would mask a pin the generator
# cannot read, which is how a moving baseline hides until someone else's branch fails
default_out="$(mktemp -d)"
if (cd "$ROOT" && python3 "$GEN" "$ROOT" --map-only "--out=$default_out" >/dev/null 2>&1); then
  assert_eq "the generator finds the pin with no base argument" "" \
    "$(diff "$MAP_BEFORE" "$default_out/docs/research/v0.23-cleanup/743-responsibilities-before.tsv" | head -5 | tr '\n' ' ')"
else
  bad "the generator does not run without an explicit base"
fi
rm -rf "$default_out"

finish "runtime responsibilities (#743)"
