#!/usr/bin/env bash
# The runtime's responsibility map is held to the tree (#743): every function in the dispatcher and its three
# modules classified exactly once, no name that does not exist, the before-change map generated by the same tool
# from the base commit, every figure on the manifest recomputed here, and the canonical primitives still canonical.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
. "$ROOT/tests/lib.sh"

MAP="$ROOT/docs/research/v0.23-cleanup/743-responsibilities.tsv"
MAP_BEFORE="$ROOT/docs/research/v0.23-cleanup/743-responsibilities-before.tsv"
MAN="$ROOT/docs/research/v0.23-cleanup/743-runtime-surface.md"
GEN="$ROOT/docs/research/v0.23-cleanup/tools/build-responsibilities.py"
SPARK="$ROOT/plugins/spark/bin/spark"
EXEC="$ROOT/plugins/spark/lib/execution.sh"
FILES="plugins/spark/bin/spark plugins/spark/lib/execution.sh plugins/spark/lib/planning.sh plugins/spark/lib/repository.sh"
for f in "$MAP" "$MAP_BEFORE" "$MAN"; do
  [ -f "$f" ] && ok || bad "$(basename "$f") is committed"
done
rows() { grep -v '^#' "$MAP" | grep -v '^$'; }
rows_before() { grep -v '^#' "$MAP_BEFORE" | grep -v '^$'; }

# --- shape and closed vocabulary, on both maps
for which in after before; do
  case "$which" in after) src=rows ;; before) src=rows_before ;; esac
  assert_eq "$which: every responsibility is in the closed vocabulary" "" \
    "$($src | cut -f3 | grep -vE '^(argument-parsing|routing-dispatch|source-collection|canonicalization|domain-semantics|evidence-authority|formatting-reporting|compatibility-fallback)$' | sort -u | tr '\n' ' ')"
  assert_eq "$which: every row has seven fields" "" "$($src | awk -F'\t' 'NF != 7 {print $1}' | tr '\n' ' ')"
  assert_eq "$which: no function is classified twice" "" "$($src | cut -f1 | sort | uniq -d | tr '\n' ' ')"
  assert_eq "$which: every file named is a runtime file" "" \
    "$($src | cut -f2 | sort -u | grep -vE '^plugins/spark/(bin/spark|lib/(execution|planning|repository)\.sh)$' | tr '\n' ' ')"
done

# --- the map is the tree's: same functions, same files, same body lengths, across all four runtime files
tree_rows=""
for f in $FILES; do
  while IFS=$'\t' read -r kind name body; do
    [ "$kind" = FUNC ] || continue
    tree_rows="$tree_rows$name	$f	$body
"
  done < <(cd "$ROOT" && bash tests/structure.sh --raw "$f")
done
assert_eq "the map names exactly the runtime's functions" \
  "$(printf '%s' "$tree_rows" | cut -f1 | sort)" "$(rows | cut -f1 | sort)"
assert_eq "every file and body length is the tree's" \
  "$(printf '%s' "$tree_rows" | sort)" "$(rows | awk -F'\t' '{printf "%s\t%s\t%s\n", $1, $2, $4}' | sort)"

# --- the before map is a real baseline: it names the base commit's runtime, not this one's
assert_eq "the manifest names the commit the before map was taken at" "1" \
  "$(grep -c 'is the same map at `[0-9a-f]\{7\}`' "$MAN")"
before_sha="$(sed -nE 's/.*is the same map at `([0-9a-f]{7})`.*/\1/p' "$MAN" | head -1)"
if (cd "$ROOT" && git cat-file -e "$before_sha^{commit}" 2>/dev/null); then
  ok
  for f in $FILES; do
    (cd "$ROOT" && git cat-file -e "$before_sha:$f" 2>/dev/null) && ok || bad "the before map's commit has no $f"
  done
else
  echo "  · the before map's commit is not in this checkout; the generator gate below still regenerates it"
fi

# --- the manifest's figures are the maps'
for r in argument-parsing routing-dispatch source-collection canonicalization domain-semantics evidence-authority formatting-reporting compatibility-fallback; do
  na="$(rows | awk -F'\t' -v r="$r" '$3 == r {c++} END {print c+0}')"
  nb="$(rows_before | awk -F'\t' -v r="$r" '$3 == r {c++} END {print c+0}')"
  la="$(rows | awk -F'\t' -v r="$r" '$3 == r {s+=$4} END {printf "%d", s}' | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')"
  lb="$(rows_before | awk -F'\t' -v r="$r" '$3 == r {s+=$4} END {printf "%d", s}' | sed ':a;s/\B[0-9]\{3\}\>/,&/;ta')"
  grep -qF -- "| \`$r\` | $nb | $na | $lb | $la |" "$MAN" && ok || bad "the manifest's row for $r is not the maps' ($nb/$na functions, $lb/$la lines)"
done
for f in $FILES; do
  na="$(rows | awk -F'\t' -v f="$f" '$2 == f {c++} END {print c+0}')"
  nb="$(rows_before | awk -F'\t' -v f="$f" '$2 == f {c++} END {print c+0}')"
  grep -qF -- "| \`$f\` | $nb | $na |" "$MAN" && ok || bad "the manifest's file row for $f is not the maps' ($nb/$na)"
done
n_after="$(rows | grep -c .)"
grep -qF -- "the $n_after functions in the dispatcher and its three modules" "$MAN" && ok || bad "the manifest does not state the runtime function count $n_after"

# --- the canonicalizations hold: one definition each, and the replaced copies are gone
for fn in intent_liveness di_trunk json_escape; do
  assert_eq "$fn is defined exactly once in the dispatcher" "1" "$(grep -c "^$fn() {" "$SPARK")"
done
assert_eq "no module restates the JSON escaper" "" \
  "$(grep -l 'json_escape_out\|bg_json_escape' "$ROOT"/plugins/spark/lib/*.sh 2>/dev/null | tr '\n' ' ')"
assert_eq "the issue-state read has one reader" "1" \
  "$(grep -c 'gh api "repos/{owner}/{repo}/issues/\$n" --jq .state' "$SPARK")"
# two readers, two facts: di_trunk answers the REMOTE trunk ref, repo_trunk the LOCAL trunk name (network-free,
# on brief's SessionStart path). Comments naming the ref do not count; executable lines do.
assert_eq "the trunk ref is read in exactly two places, one per fact" "2" \
  "$(grep -v '^ *#' "$SPARK" | grep -c 'refs/remotes/origin/HEAD')"
assert_eq "resume calls the remote-trunk reader" "1" \
  "$(awk '/^cmd_resume\(\) \{/, /^\}/' "$SPARK" | grep -c 'di_trunk "\$root"')"
assert_eq "resume does not resolve the ref itself" "0" \
  "$(awk '/^cmd_resume\(\) \{/, /^\}/' "$SPARK" | grep -v '^ *#' | grep -c 'refs/remotes/origin/HEAD')"

# --- the map proves the canonicalization across the module boundary, which a dispatcher-only graph could not
je="$(rows | awk -F'\t' '$1 == "json_escape" {print $6}')"
for consumer in cmd_state cmd_telemetry cmd_budget; do
  case "$je" in
    *"$consumer"*) ok ;;
    *) bad "the map does not show $consumer consuming json_escape" ;;
  esac
done
grep -q 'json_escape' "$EXEC" && ok || bad "the execution module calls the canonical escaper"

# --- the primitives are used, not merely defined
for fn in intent_liveness di_trunk json_escape; do
  n="$(rows | awk -F'\t' -v f="$fn" '$1 == f {print $5}')"
  [ "${n:-0}" -ge 2 ] && ok || bad "$fn is defined but has fewer than two consumers"
done

# --- the generator is runnable, and both committed maps are what it produces
[ -x "$GEN" ] && ok || bad "the map's generator is committed and executable"
[ -f "$ROOT/docs/research/v0.23-cleanup/tools/classification.py" ] && ok || bad "the dispatcher classification is committed under an importable name"
[ -f "$ROOT/docs/research/v0.23-cleanup/tools/classification_modules.py" ] && ok || bad "the module classification is committed under an importable name"
gen_out="$(mktemp -d)"
if (cd "$ROOT" && python3 "$GEN" "$ROOT" --map-only "--out=$gen_out" >/dev/null 2>&1); then
  assert_eq "the committed map is what the generator produces" "" \
    "$(diff "$MAP" "$gen_out/docs/research/v0.23-cleanup/743-responsibilities.tsv" | head -5 | tr '\n' ' ')"
  assert_eq "the committed before map is what the generator produces" "" \
    "$(diff "$MAP_BEFORE" "$gen_out/docs/research/v0.23-cleanup/743-responsibilities-before.tsv" | head -5 | tr '\n' ' ')"
else
  bad "the map's generator does not run"
fi
rm -rf "$gen_out"

finish "runtime responsibilities (#743)"
